// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['AlterTable'](arg1, arg2, arg3, arg4);
}

export function CancelQuery(arg1, arg2) {
  return window['go']['backend']['App']['CancelQuery'](arg1, arg2);
}

export function ClearQueryHistory(arg1) {
  return window['go']['backend']['App']['ClearQueryHistory'](arg1);
}

export function CompareAndGenerateScript(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CompareAndGenerateScript'](arg1, arg2, arg3, arg4);
}

export function CompareSchemas(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CompareSchemas'](arg1, arg2, arg3, arg4);
}

export function CompareSchemasWithTables(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CompareSchemasWithTables'](arg1, arg2, arg3, arg4, arg5);
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['backend']['App']['CreateProfile'](arg1);
}

export function CreateTable(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateTable'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['App']['DeleteProfile'](arg1);
}

export function DeleteRows(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['DeleteRows'](arg1, arg2, arg3, arg4);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['backend']['App']['DeleteSavedQuery'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function DropTable(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DropTable'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['backend']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteQueryWithTimeout(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExecuteQueryWithTimeout'](arg1, arg2, arg3);
}

export function ExecuteSyncScript(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ExecuteSyncScript'](arg1, arg2, arg3, arg4);
}

export function ExportToCSV(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ExportToCSV'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportToJSON(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ExportToJSON'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportToSQL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ExportToSQL'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateSyncScript(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GenerateSyncScript'](arg1, arg2, arg3, arg4);
}

export function GetConnectionStatus(arg1) {
  return window['go']['backend']['App']['GetConnectionStatus'](arg1);
}

export function GetCreateTableDDL(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetCreateTableDDL'](arg1, arg2, arg3);
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['backend']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetRowCount(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetRowCount'](arg1, arg2, arg3, arg4);
}

export function GetSavedQueries(arg1) {
  return window['go']['backend']['App']['GetSavedQueries'](arg1);
}

export function GetSavedQuery(arg1) {
  return window['go']['backend']['App']['GetSavedQuery'](arg1);
}

export function GetSyncSummary(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetSyncSummary'](arg1, arg2, arg3);
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function ImportFromCSV(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ImportFromCSV'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportFromJSON(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ImportFromJSON'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportFromSQL(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ImportFromSQL'](arg1, arg2, arg3);
}

export function InsertRow(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['InsertRow'](arg1, arg2, arg3, arg4);
}

export function ListDatabases(arg1) {
  return window['go']['backend']['App']['ListDatabases'](arg1);
}

export function ListProfiles() {
  return window['go']['backend']['App']['ListProfiles']();
}

export function ListTables(arg1, arg2) {
  return window['go']['backend']['App']['ListTables'](arg1, arg2);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['backend']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['backend']['App']['OpenFileDialog'](arg1, arg2);
}

export function QueryData(arg1, arg2) {
  return window['go']['backend']['App']['QueryData'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SaveQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['SaveQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function SyncTableData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['SyncTableData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['backend']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateRow'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSavedQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateSavedQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateCSVFormat(arg1, arg2) {
  return window['go']['backend']['App']['ValidateCSVFormat'](arg1, arg2);
}

export function ValidateJSONFormat(arg1, arg2) {
  return window['go']['backend']['App']['ValidateJSONFormat'](arg1, arg2);
}

export function ValidateSQLFormat(arg1, arg2) {
  return window['go']['backend']['App']['ValidateSQLFormat'](arg1, arg2);
}

export function ValidateSyncScript(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ValidateSyncScript'](arg1, arg2, arg3);
}
