// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';
import {types} from '../models';
import {query} from '../models';
import {repository} from '../models';
import {storage} from '../models';
import {importexport} from '../models';
import {backend} from '../models';

export function AlterTable(arg1:string,arg2:string,arg3:string,arg4:schema.TableSchema):Promise<void>;

export function CancelQuery(arg1:string,arg2:string):Promise<void>;

export function ClearQueryHistory(arg1:string):Promise<void>;

export function CompareAndGenerateScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<types.SchemaDiff>;

export function CompareSchemas(arg1:string,arg2:string,arg3:string,arg4:string):Promise<types.SchemaDiff>;

export function CompareSchemasWithTables(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<types.SchemaDiff>;

export function Connect(arg1:string):Promise<void>;

export function CreateProfile(arg1:types.ConnectionProfile):Promise<void>;

export function CreateTable(arg1:string,arg2:string,arg3:schema.TableSchema):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRows(arg1:string,arg2:string,arg3:string,arg4:Array<Record<string, any>>):Promise<number>;

export function DeleteSavedQuery(arg1:number):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DropTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<query.QueryResult>;

export function ExecuteQueryWithTimeout(arg1:string,arg2:string,arg3:number):Promise<query.QueryResult>;

export function ExecuteSyncScript(arg1:string,arg2:string,arg3:string,arg4:types.SyncScript):Promise<void>;

export function ExportToCSV(arg1:string,arg2:string,arg3:string,arg4:repository.DataQuery,arg5:string):Promise<void>;

export function ExportToJSON(arg1:string,arg2:string,arg3:string,arg4:repository.DataQuery,arg5:string):Promise<void>;

export function ExportToSQL(arg1:string,arg2:string,arg3:string,arg4:repository.DataQuery,arg5:string):Promise<void>;

export function GenerateSyncScript(arg1:string,arg2:string,arg3:string,arg4:types.SchemaDiff):Promise<types.SyncScript>;

export function GetConnectionStatus(arg1:string):Promise<string>;

export function GetCreateTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetQueryHistory(arg1:string,arg2:number):Promise<Array<storage.QueryHistoryEntry>>;

export function GetRowCount(arg1:string,arg2:string,arg3:string,arg4:Array<repository.Filter>):Promise<number>;

export function GetSavedQueries(arg1:string):Promise<Array<storage.SavedQuery>>;

export function GetSavedQuery(arg1:number):Promise<storage.SavedQuery>;

export function GetSyncSummary(arg1:string,arg2:string,arg3:types.SchemaDiff):Promise<string>;

export function GetTableSchema(arg1:string,arg2:string,arg3:string):Promise<schema.TableSchema>;

export function Greet(arg1:string):Promise<string>;

export function ImportFromCSV(arg1:string,arg2:string,arg3:string,arg4:string,arg5:importexport.ColumnMapping):Promise<importexport.ImportResult>;

export function ImportFromJSON(arg1:string,arg2:string,arg3:string,arg4:string,arg5:importexport.ColumnMapping):Promise<importexport.ImportResult>;

export function ImportFromSQL(arg1:string,arg2:string,arg3:string):Promise<importexport.ImportResult>;

export function InsertRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function ListDatabases(arg1:string):Promise<Array<repository.Database>>;

export function ListProfiles():Promise<Array<types.ConnectionProfile>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<repository.Table>>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:Array<backend.FileDialogFilter>):Promise<string>;

export function QueryData(arg1:string,arg2:repository.DataQuery):Promise<repository.DataResult>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<backend.FileDialogFilter>):Promise<string>;

export function SaveQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function SyncTableData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function TestConnection(arg1:types.ConnectionProfile):Promise<void>;

export function UpdateProfile(arg1:string,arg2:types.ConnectionProfile):Promise<void>;

export function UpdateRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>,arg5:Record<string, any>):Promise<void>;

export function UpdateSavedQuery(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ValidateCSVFormat(arg1:string,arg2:string):Promise<void>;

export function ValidateJSONFormat(arg1:string,arg2:string):Promise<void>;

export function ValidateSQLFormat(arg1:string,arg2:string):Promise<void>;

export function ValidateSyncScript(arg1:string,arg2:string,arg3:types.SyncScript):Promise<void>;
